'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Locations', [
      {
        location_name: 'Bãi đỗ xe Hòa Khánh',
        user_id: 1,
        address: '12 Đường số 5',
        city: 'Đà Nẵng',
        district: 'Liên Chiểu',
        ward: 'Hòa Khánh',
        lat: 16.0678,
        lng: 108.1768,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Bãi đỗ xe Nguyễn Văn Linh',
        user_id: 2,
        address: '234 Nguyễn Văn Linh',
        city: 'Đà Nẵng',
        district: 'Hải Châu',
        ward: 'Nam Dương',
        lat: 16.0565,
        lng: 108.2137,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Trạm sạc Lê Văn Hiến',
        user_id: 3,
        address: '56 Lê Văn Hiến',
        city: 'Đà Nẵng',
        district: 'Ngũ Hành Sơn',
        ward: 'Khuê Mỹ',
        lat: 16.0187,
        lng: 108.2525,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Bãi đỗ xe Nguyễn Hữu Thọ',
        user_id: 4,
        address: '89 Nguyễn Hữu Thọ',
        city: 'Đà Nẵng',
        district: 'Hải Châu',
        ward: 'Hòa Thuận Tây',
        lat: 16.0354,
        lng: 108.2146,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Trạm xăng Hòa Minh',
        user_id: 5,
        address: '22 Nguyễn Lương Bằng',
        city: 'Đà Nẵng',
        district: 'Liên Chiểu',
        ward: 'Hòa Minh',
        lat: 16.0725,
        lng: 108.1846,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Bãi đỗ xe An Hải',
        user_id: 6,
        address: '78 An Hải Bắc',
        city: 'Đà Nẵng',
        district: 'Sơn Trà',
        ward: 'An Hải Bắc',
        lat: 16.0773,
        lng: 108.2391,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Bãi đỗ xe Bạch Đằng',
        user_id: 7,
        address: '123 Bạch Đằng',
        city: 'Đà Nẵng',
        district: 'Hải Châu',
        ward: 'Hải Châu 1',
        lat: 16.0679,
        lng: 108.2234,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Trạm sạc Nguyễn Tri Phương',
        user_id: 8,
        address: '45 Nguyễn Tri Phương',
        city: 'Đà Nẵng',
        district: 'Thanh Khê',
        ward: 'Thanh Khê Đông',
        lat: 16.0554,
        lng: 108.1943,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Bãi đỗ xe Núi Thành',
        user_id: 9,
        address: '90 Núi Thành',
        city: 'Đà Nẵng',
        district: 'Hải Châu',
        ward: 'Hòa Cường Nam',
        lat: 16.0435,
        lng: 108.2158,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Trạm sạc Phạm Văn Đồng',
        user_id: 10,
        address: '112 Phạm Văn Đồng',
        city: 'Đà Nẵng',
        district: 'Sơn Trà',
        ward: 'An Hải Bắc',
        lat: 16.0770,
        lng: 108.2399,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Bãi đỗ xe Điện Biên Phủ',
        user_id: 11,
        address: '150 Điện Biên Phủ',
        city: 'Đà Nẵng',
        district: 'Thanh Khê',
        ward: 'Chính Gián',
        lat: 16.0653,
        lng: 108.1915,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Bãi đỗ xe Nguyễn Văn Cừ',
        user_id: 12,
        address: '32 Nguyễn Văn Cừ',
        city: 'Đà Nẵng',
        district: 'Liên Chiểu',
        ward: 'Hòa Hiệp Nam',
        lat: 16.0973,
        lng: 108.1643,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Trạm xăng Ngô Quyền',
        user_id: 13,
        address: '102 Ngô Quyền',
        city: 'Đà Nẵng',
        district: 'Sơn Trà',
        ward: 'An Hải Bắc',
        lat: 16.0824,
        lng: 108.2395,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Bãi đỗ xe Hùng Vương',
        user_id: 14,
        address: '45 Hùng Vương',
        city: 'Đà Nẵng',
        district: 'Hải Châu',
        ward: 'Hải Châu 1',
        lat: 16.0699,
        lng: 108.2201,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Bãi đỗ xe Trần Cao Vân',
        user_id: 15,
        address: '30 Trần Cao Vân',
        city: 'Đà Nẵng',
        district: 'Thanh Khê',
        ward: 'Tam Thuận',
        lat: 16.0708,
        lng: 108.2051,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Trạm sạc Lý Thái Tổ',
        user_id: 16,
        address: '80 Lý Thái Tổ',
        city: 'Đà Nẵng',
        district: 'Hải Châu',
        ward: 'Thạch Thang',
        lat: 16.0731,
        lng: 108.2198,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Bãi đỗ xe Tôn Đức Thắng',
        user_id: 17,
        address: '140 Tôn Đức Thắng',
        city: 'Đà Nẵng',
        district: 'Liên Chiểu',
        ward: 'Hòa Minh',
        lat: 16.0775,
        lng: 108.1774,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Trạm sạc Võ Văn Kiệt',
        user_id: 18,
        address: '15 Võ Văn Kiệt',
        city: 'Đà Nẵng',
        district: 'Sơn Trà',
        ward: 'Phước Mỹ',
        lat: 16.0690,
        lng: 108.2399,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Bãi đỗ xe Hoàng Diệu',
        user_id: 19,
        address: '77 Hoàng Diệu',
        city: 'Đà Nẵng',
        district: 'Hải Châu',
        ward: 'Hải Châu 2',
        lat: 16.0621,
        lng: 108.2207,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Trạm sạc Trần Phú',
        user_id: 20,
        address: '9 Trần Phú',
        city: 'Đà Nẵng',
        district: 'Hải Châu',
        ward: 'Hải Châu 1',
        lat: 16.0672,
        lng: 108.2223,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Bãi đỗ xe Phan Châu Trinh',
        user_id: 21,
        address: '102 Phan Châu Trinh',
        city: 'Đà Nẵng',
        district: 'Hải Châu',
        ward: 'Phước Ninh',
        lat: 16.0638,
        lng: 108.2205,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Bãi đỗ xe Nguyễn Chí Thanh',
        user_id: 22,
        address: '55 Nguyễn Chí Thanh',
        city: 'Đà Nẵng',
        district: 'Hải Châu',
        ward: 'Hải Châu 1',
        lat: 16.0700,
        lng: 108.2180,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Trạm sạc Lê Đình Lý',
        user_id: 23,
        address: '28 Lê Đình Lý',
        city: 'Đà Nẵng',
        district: 'Thanh Khê',
        ward: 'Thạc Gián',
        lat: 16.0550,
        lng: 108.2027,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Bãi đỗ xe Nguyễn Tất Thành',
        user_id: 24,
        address: '222 Nguyễn Tất Thành',
        city: 'Đà Nẵng',
        district: 'Thanh Khê',
        ward: 'Xuân Hà',
        lat: 16.0795,
        lng: 108.1899,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Trạm sạc Hàm Nghi',
        user_id: 25,
        address: '65 Hàm Nghi',
        city: 'Đà Nẵng',
        district: 'Thanh Khê',
        ward: 'Vĩnh Trung',
        lat: 16.0598,
        lng: 108.2035,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Bãi đỗ xe Trần Hưng Đạo',
        user_id: 26,
        address: '120 Trần Hưng Đạo',
        city: 'Đà Nẵng',
        district: 'Sơn Trà',
        ward: 'An Hải Tây',
        lat: 16.0739,
        lng: 108.2347,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Trạm sạc Nguyễn Hữu Thọ 2',
        user_id: 27,
        address: '200 Nguyễn Hữu Thọ',
        city: 'Đà Nẵng',
        district: 'Hải Châu',
        ward: 'Hòa Cường Bắc',
        lat: 16.0412,
        lng: 108.2130,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Bãi đỗ xe Lê Lợi',
        user_id: 28,
        address: '17 Lê Lợi',
        city: 'Đà Nẵng',
        district: 'Hải Châu',
        ward: 'Hải Châu 1',
        lat: 16.0705,
        lng: 108.2209,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Trạm sạc Phan Đăng Lưu',
        user_id: 29,
        address: '30 Phan Đăng Lưu',
        city: 'Đà Nẵng',
        district: 'Hải Châu',
        ward: 'Hòa Thuận Đông',
        lat: 16.0450,
        lng: 108.2185,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Bãi đỗ xe Duy Tân',
        user_id: 30,
        address: '88 Duy Tân',
        city: 'Đà Nẵng',
        district: 'Hải Châu',
        ward: 'Hòa Thuận Đông',
        lat: 16.0465,
        lng: 108.2187,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Bãi đỗ xe 1',
        user_id: 31,
        address: '123 Lê Duẩn',
        city: 'Đà Nẵng',
        district: 'Hải Châu',
        ward: 'Hoà Thuận',
        lat: 16.0471,
        lng: 108.22,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Bãi đỗ xe 10',
        user_id: 32,
        address: '124 Lê Duẩn',
        city: 'Đà Nẵng',
        district: 'Hải Châu',
        ward: 'Hoà Thuận',
        lat: 16.0472,
        lng: 108.22,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Bãi đỗ xe 2',
        user_id: 33,
        address: '68 Võ Chí Công',
        city: 'Đà Nẵng',
        district: 'Ngũ Hành Sơn',
        ward: 'Hoà Quý',
        lat: 16.0471,
        lng: 108.22,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Bãi đỗ xe 13',
        user_id: 34,
        address: '23 Bình Kỳ',
        city: 'Đà Nẵng',
        district: 'Ngũ Hành Sơn',
        ward: 'Hoà Quý',
        lat: 16.0471,
        lng: 200,   // có thể cần kiểm tra
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'xe 2',
        user_id: 35,
        address: '123 Mai Đăng Chơn',
        city: 'Đà Nẵng',
        district: 'Ngũ Hành Sơn',
        ward: 'Hoà Quý',
        lat: 95,
        lng: 108.22,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Bãi đỗ xe 4',
        user_id: 36,
        address: '123 Nguyễn Hữu Thọ',
        city: 'Đà Nẵng',
        district: 'Hải Châu',
        ward: 'Hoà Thuận Tây',
        lat: 95,
        lng: 108.22,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Bãi đỗ xe 1',
        user_id: 37,
        address: '123 Lê Duẩn',
        city: 'Đà Nẵng',
        district: 'Hải Châu',
        ward: 'Hoà Thuận',
        lat: 16.0471,
        lng: 108.22,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        location_name: 'Trạm xăng',
        user_id: 38,
        address: '123 Lê Duẩn',
        city: 'Đà Nẵng',
        district: 'Hải Châu',
        ward: 'Hoà Thuận',
        lat: 16.0471,
        lng: 108.22,
        createdAt: new Date(),
        updatedAt: new Date()
      }
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    
  }
};
