'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Users', [
      {
        email: 'nguyenvana@example.com',
        password: 'Anh12345',
        firstName: 'Nguyễn',
        lastName: 'Văn A',
        address: '123 Lý Thường Kiệt, Hà Nội',
        phonenumber: '0912345678',
        gender: 'M',
        image: null,
        roleId: 'R1',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'danghoang@example.com',
        password: 'Anh12345',
        firstName: 'Đặng',
        lastName: 'Hoàng',
        address: '654 Trần Hưng Đạo, Hải Phòng',
        phonenumber: '0954345678',
        gender: 'M',
        image: null,
        roleId: 'R1',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'hoangnam@example.com',
        password: 'Anh12345',
        firstName: 'Hoàng',
        lastName: 'Nam',
        address: '222 Nguyễn Huệ, Đà Nẵng',
        phonenumber: '0976567890',
        gender: 'M',
        image: null,
        roleId: 'R1',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
       {
        email: 'doanphuong@example.com',
        password: 'Anh12345',
        firstName: 'Đoàn',
        lastName: 'Phương',
        address: '555 Võ Nguyên Giáp, TP.HCM',
        phonenumber: '0909890123',
        gender: 'M',
        image: null,
        roleId: 'R1',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'tranvuthanh@example.com',
        password: 'Anh12345',
        firstName: 'Trần',
        lastName: 'Vũ Thành',
        address: '777 Trường Chinh, TP.HCM',
        phonenumber: '0921212345',
        gender: 'M',
        image: null,
        roleId: 'R1',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'vothien@example.com',
        password: 'Anh12345',
        firstName: 'Võ',
        lastName: 'Thiện',
        address: '111 Nguyễn Tri Phương, Đà Nẵng',
        phonenumber: '0954545678',
        gender: 'M',
        image: null,
        roleId: 'R1',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'kiennguyen@example.com',
        password: 'Anh12345',
        firstName: 'Kiên',
        lastName: 'Nguyễn',
        address: '444 Trần Phú, Nha Trang',
        phonenumber: '0987878901',
        gender: 'M',
        image: null,
        roleId: 'R1',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'phamhuong@example.com',
        password: 'Anh12345',
        firstName: 'Phạm',
        lastName: 'Hương',
        address: '888 Bà Triệu, Hà Nội',
        phonenumber: '0921212345',
        gender: 'F',
        image: null,
        roleId: 'R1',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'tranbinh@example.com',
        password: 'Anh12345',
        firstName: 'Trần',
        lastName: 'Bình',
        address: '999 Hoàng Hoa Thám, Huế',
        phonenumber: '0932323456',
        gender: 'M',
        image: null,
        roleId: 'R1',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'trinhhoai@example.com',
        password: 'Anh12345',
        firstName: 'Trịnh',
        lastName: 'Hoài',
        address: '999 Nguyễn Văn Cừ, Huế',
        phonenumber: '0943434567',
        gender: 'F',
        image: null,
        roleId: 'R2',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'tranthibe@example.com',
        password: 'Anh12345',
        firstName: 'Trần',
        lastName: 'Thị Be',
        address: '456 Nguyễn Trãi, TP.HCM',
        phonenumber: '0987654321',
        gender: 'F',
        image: null,
        roleId: 'R2',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'phamthid@example.com',
        password: 'Anh12345',
        firstName: 'Phạm',
        lastName: 'Thị Duyen',
        address: '321 Điện Biên Phủ, Cần Thơ',
        phonenumber: '0943234567',
        gender: 'F',
        image: null,
        roleId: 'R2',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
       {
        email: 'buitran@example.com',
        password: 'Anh12345',
        firstName: 'Bùi',
        lastName: 'Trân',
        address: '111 Quang Trung, Huế',
        phonenumber: '0965456789',
        gender: 'F',
        image: null,
        roleId: 'R2',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'ngothuh@example.com',
        password: 'Anh12345',
        firstName: 'Ngô',
        lastName: 'Thu H',
        address: '333 Lê Duẩn, Hà Nội',
        phonenumber: '0987678901',
        gender: 'F',
        image: null,
        roleId: 'R2',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'nguyenthuy@example.com',
        password: 'Anh12345',
        firstName: 'Nguyễn',
        lastName: 'Thúy',
        address: '444 Bạch Đằng, Hải Phòng',
        phonenumber: '0998789012',
        gender: 'F',
        image: null,
        roleId: 'R2',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'maithanh@example.com',
        password: 'Anh12345',
        firstName: 'Mai',
        lastName: 'Thanh',
        address: '222 Hoàng Diệu, Hà Nội',
        phonenumber: '0965656789',
        gender: 'F',
        image: null,
        roleId: 'R2',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'phamson@example.com',
        password: 'Anh12345',
        firstName: 'Phạm',
        lastName: 'Sơn',
        address: '555 Lý Nam Đế, Hà Nội',
        phonenumber: '0998989012',
        gender: 'M',
        image: null,
        roleId: 'R2',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'vothu@example.com',
        password: 'Anh12345',
        firstName: 'Võ',
        lastName: 'Thu',
        address: '777 Nguyễn Thái Học, Đà Nẵng',
        phonenumber: '0910101234',
        gender: 'F',
        image: null,
        roleId: 'R2',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'maihanh@example.com',
        password: 'Anh12345',
        firstName: 'Mai',
        lastName: 'Hạnh',
        address: '234 Nguyễn Văn Linh, Đà Nẵng',
        phonenumber: '0954545678',
        gender: 'F',
        image: null,
        roleId: 'R2',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'phamnga@example.com',
        password: 'Anh12345',
        firstName: 'Phạm',
        lastName: 'Nga',
        address: '678 Cách Mạng Tháng 8, Cần Thơ',
        phonenumber: '0998989012',
        gender: 'F',
        image: null,
        roleId: 'R2',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'nguyenviet@example.com',
        password: 'Anh12345',
        firstName: 'Nguyễn',
        lastName: 'Việt',
        address: '456 Lê Quý Đôn, TP.HCM',
        phonenumber: '0976767890',
        gender: 'M',
        image: null,
        roleId: 'R3',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'truonggiang@example.com',
        password: 'Anh12345',
        firstName: 'Trương',
        lastName: 'Giang',
        address: '567 Phạm Văn Đồng, Nha Trang',
        phonenumber: '0987878901',
        gender: 'M',
        image: null,
        roleId: 'R3',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'leminhchinh@example.com',
        password: 'Anh12345',
        firstName: 'Lê',
        lastName: 'Minh Chinh',
        address: '789 Lê Lợi, Đà Nẵng',
        phonenumber: '0932123456',
        gender: 'M',
        image: null,
        roleId: 'R3',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'phanvanhoang@example.com',
        password: 'Anh12345',
        firstName: 'Phan',
        lastName: 'Văn Hoang',
        address: '666 Phan Chu Trinh, Đà Lạt',
        phonenumber: '0910101234',
        gender: 'M',
        image: null,
        roleId: 'R3',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'luuthanh@example.com',
        password: 'Anh12345',
        firstName: 'Lưu',
        lastName: 'Thành',
        address: '888 Tôn Đức Thắng, Hà Nội',
        phonenumber: '0932323456',
        gender: 'M',
        image: null,
        roleId: 'R3',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'phunglinh@example.com',
        password: 'Anh12345',
        firstName: 'Phùng',
        lastName: 'Linh',
        address: '333 Kim Mã, TP.HCM',
        phonenumber: '0976767890',
        gender: 'F',
        image: null,
        roleId: 'R3',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'tranthu@example.com',
        password: 'Anh12345',
        firstName: 'Trần',
        lastName: 'Thu',
        address: '666 Trần Quốc Toản, Cần Thơ',
        phonenumber: '0909090123',
        gender: 'F',
        image: null,
        roleId: 'R3',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'letrang@example.com',
        password: 'Anh12345',
        firstName: 'Lê',
        lastName: 'Trang',
        address: '123 Điện Biên Phủ, Hải Phòng',
        phonenumber: '0943434567',
        gender: 'F',
        image: null,
        roleId: 'R3',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'vuphuong@example.com',
        password: 'Anh12345',
        firstName: 'Vũ',
        lastName: 'Phương',
        address: '345 Hoàng Văn Thụ, Hà Nội',
        phonenumber: '0965656789',
        gender: 'F',
        image: null,
        roleId: 'R3',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        email: 'hoanganh@example.com',
        password: 'Anh12345',
        firstName: 'Hoàng',
        lastName: 'Anh',
        address: '789 Trần Hưng Đạo, Hải Dương',
        phonenumber: '0909090123',
        gender: 'M',
        image: null,
        roleId: 'R3',
        ban: 0,
        createdAt: new Date(),
        updatedAt: new Date()
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
  }
};
